### ISSUE TITLE
CssPropertySelectedTabHighlightThickness from plugin.xml not found in repo

### ISSUE THREAD

**Issue by BeckerWdf** [gayanper/eclipse-themes#51]
I do not finde the CssPropertySelectedTabHighlightThickness class that is referenced in the plugin.xml.
Is this a left-over?

**Comment by gayanper** [comment]
> I do not finde the CssPropertySelectedTabHighlightThickness class that is referenced in the plugin.xml.
> Is this a left-over?

Yes i will clean it up today. It was a WIP feature i was trying by using a copy of the renderer and introducing thickness support. But i later decided to contribute that feature into platform and getting that support. I missed to cleanup the css file.

**Comment by rgrunber** [comment]
Ran into this at runtime also :

```
!ENTRY org.eclipse.e4.ui.css.core 4 0 2022-05-30 12:53:51.665
!MESSAGE invalid property handler for null: org.eclipse.core.runtime.CoreException: Plug-in org.gap.eclipse.themes was unable to load class org.gap.eclipse.themes.e4.renders.swt.CssPropertySelectedTabHighlightThickness.
```

I also don't see the theme at all in the "Theme" dropdown of the "Apperance" preference page. I guess this is related ?

**Comment by gayanper** [comment]
@rgrunber @BeckerWdf check with the latest changes now.

**Comment by rgrunber** [comment]
@gayanper After trying the latest build I don't see any more errors. However, the "Theme" combo box of the "Appearance" preference page. I'm on Fedora 36 (Linux). Would https://github.com/gayanper/eclipse-themes/blob/main/themes/plugin.xml imply there's no Linux support currently ?

**Comment by gayanper** [comment]
@rgrunber yes since I don’t have a linux box right now for testing I didn’t add the support. But if you can test it and if it works we can enable linux support as well. I think i need to setup some vms for testing going forward
